(part "TS02-66-50-BK-260-LCR-D"
    (packageRef "TS026650BK260LCRD")
    (interface
        (port "1" (symbPinId 1) (portName "NO_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NO_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "COM_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "COM_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "179-TS026650BK260LCR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/TS02-66-50-BK-260-LCR-D?qs=A6eO%252BMLsxmSvgpm8sQwHAQ%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "TS02-66-50-BK-260-LCR-D")
    (property "Description" "6 x 6 mm, 5 mm Actuator Height, 260 gf, Black, Long Crimped, Through Hole, SPST, Tactile Switch")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/ts02.pdf")
    (property "symbolName1" "TS02-66-50-BK-260-LCR-D")
)
